### ISSUE TITLE
Add filter for which meta keys to track in action monitor

### ISSUE THREAD

**Issue by jasonbahl** [gatsbyjs/wp-gatsby#39] opened 2020-10-21 22:56 UTC
Right now action monitor actions are created for all meta updates. 

We should add a filter to allow users to opt out of tracking if a meta key/value meets criteria they want to go untracked.

**Comment by TylerBarnes** [comment] 2020-11-19 18:21
Closing as a duplicate of #38

**Closed by TylerBarnes** 2020-11-19 18:21 UTC
Labels: priority: medium
