### ISSUE TITLE
Build hooks not firing

### ISSUE THREAD

**Issue by michaelpanik** [gatsbyjs/wp-gatsby#129] opened 2021-02-12 22:33 UTC
I have my custom build webhook endpoint configured in Settings › WPGatsby. I updated a post and see that the action is recorded in Action Monitor. I've verified that POSTing to the endpoint functions as expected and that the server is able to send a POST request to the endpoint.

Any possible reasons that the hook wouldn't be called when editing content? It was previously working, but we're not sure at what point/what change it quit working.

WPGatsby @ 1.0.3
WP GraphQL @ 1.1.3

**Comment by michaelpanik** [comment] 2021-02-15 17:45
After some digging, it seems like `$should_dispatch` in the `ActionMonitor` class is always false, only set to true when `schedule_dispatch()` is called. It looks like that function is never called. That means in `trigger_dispatch()`, on line 655, `$this->should_dispatch()` is always false, so `$should_call_build_webhooks` is always false, so the conditional block starting on line 661 will never run and the build hook is not fired.

**Comment by jacksellwood** [comment] 2021-03-16 18:20
Hi Michael, we'd like to take a look at this in closer detail. Could you invite wordpress@gatsbyjs.com to your WordPress site? Additionally, please use the free tier of Gatsby Cloud to spin up a site. We'll use these two things to debug why content changes aren't caught by action monitor.

**Comment by tiddydl** [comment] 2021-03-22 23:44
Hello, I have the same problem and I just could reproduce it: When I use the same "User-Agent" that Wordpress sends to gatsbyjs.com (`User-Agent: WordPress\5.7`), the build trigger doesn't work. If I use any different User-Agent, the build trigger works.

**Comment by TylerBarnes** [comment] 2021-03-23 18:05
@sslotsky this sounds like a problem with per-source refreshes. My guess is that WP used to send `User-Agent: WordPress` but it now includes the version number (not 100% sure about that). What do you think?

**Comment by sslotsky** [comment] 2021-03-23 18:10
We don't do a strict equality check there though 🤔 

```ts
  if (userAgent && userAgent.includes(`WordPress`)) {
```

**Comment by tiddydl** [comment] 2021-03-24 07:23
Hi again! So weird, as if it appears the word `WordPress` (with or without version), the trigger build doesn't work. If you can't reproduce it, I can share with you privately some sites in gatsbyjs.com so you can reproduce it.

Thanks for your support!

**Comment by TylerBarnes** [comment] 2021-03-24 22:13
@tiddydl that would be super helpful

**Comment by adel0559** [comment] 2021-03-29 14:33
Hi! Not sure what the status is on this but I'm running into the same issue. I can confirm that when using a user-agent containing the exact phrase "WordPress" it fails but anything else succeeds. Feels like it should be the other way around?

**Comment by jacksellwood** [comment] 2021-03-30 18:23
Hey there! This requires some more investigation, and we'll plan to do that in an upcoming sprint. Could you open a ticket from Gatsby Cloud and include a link to this GH issue? This will let us know which exact sites to investigate.

**Comment by EdPike365** [comment] 2021-03-31 00:05
When I use the provided build URL in postman, I get a 204, but nothing is showing on the Builds Tab list. I am on the free plan. All settings on the app are default. I am not using a CMS. I just have the starter blog on Gatsby Cloud.  I have pushed the change to GitHub on the build branch. I pushed a similar change before and used the "Trigger build" button and it worked fine. I'm about to do it again to see if something is wrong with Gatsby Cloud.

**Comment by tiddydl** [comment] 2021-03-31 06:38
@TylerBarnes @jacksellwood I just reported it through Gatsbyjs, adding two sites where I could reproduce it.
I hope this is resolved soon! 🙌

**Comment by TylerBarnes** [comment] 2021-04-08 20:26
Hi again everyone, we believe we've fixed this issue. We identified and fixed an issue that manifested the same way as this issue. Before we close this can you confirm that it's working for you?

**Comment by tiddydl** [comment] 2021-04-12 16:48
Is working! Thank you @TylerBarnes and team :)

**Closed** 2021-04-13 18:25 UTC
Labels: needs reproduction
