### ISSUE TITLE
GRAPHQL_DEBUG always enabled

### ISSUE THREAD

**Issue by lnikell** [gatsbyjs/wp-gatsby#103] opened 2021-01-14 17:29 UTC
Hi, I found that there is no way to set "GRAPHQL_DEBUG" as false

![image](https://user-images.githubusercontent.com/2697570/104626317-0db54a00-5696-11eb-8938-554d2d10b0fb.png)

It's set on the plugin level as true in that file
/wp-content/plugins/wp-gatsby/tests/_data/config.php

I'm sure it should not work this way, but if I comment on this line everything starts to work as expected 
![image](https://user-images.githubusercontent.com/2697570/104626569-5c62e400-5696-11eb-84d0-786526547809.png)

wp-gatsby - version 0.9.1

**Comment by jasonbahl** [comment] 2021-01-15 08:54
Closing as this looks to be a duplicate of #104

**Closed by jasonbahl** 2021-01-15 08:54 UTC
